Port to XCP-ng, without optional features, with updated gnutls
This package is needed by nbdkit, it has been reduced to avoid pulling
more dependencies.

Rebuild without ocaml, appliance and daemon

daemon is disabled to prevent this issue:

    guestfsd-stubs-0.o: In function `mount_9p_stub':
    libguestfs-1.36.10/daemon/stubs-0.c:1851: undefined reference to `do_mount_9p'
    guestfsd-stubs-6.o: In function `list_9p_stub':
    libguestfs-1.36.10/daemon/stubs-6.c:1319: undefined reference to `do_list_9p'
    collect2: error: ld returned 1 exit status

Force qemu-img to overcomme the blktap clash

Signed-off-by: Philippe Coval <philippe.coval@vates.tech>